[package]
name = "rtx"
version = "0.1.0"
authors = ["baotran"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rtx"
path = "rtx/src/lib.rs"

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
rand = "0.7"
